---
title: "UNICEF Database Manager Assessment"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```
The code below is a part of the UNICEF Database Manager Assessment project. 


```{r wd set up, include=FALSE}
#the wd needs to be customized to local path in order reproduce the text 
wd = "/Users/karavan88/Documents/GitHub/unf_db_test"
setwd(wd)

# Check if the file exists before sourcing
user_profile_path <- file.path(wd, "user_profile.R")
dir.exists(user_profile_path)
```

```{r source files, include=FALSE}
source(file.path(wd,           "user_profile.R"))
# source(file.path(rCodes,     "00_user_functions.R"))
# source(file.path(codesTask1, "0101_data_prep.R"))
# source(file.path(codesTask1, "0102_data_analysis.R"))
# source(file.path(codesTask1, "0103_data_vis.R"))
```


## Task 1. MNCH and U5MR indicators

The first task is to calculate population-weighted coverage of health services (antenatal care and skilled birth attendance) for countries categorized as on-track and off-track in achieving under-5 mortality targets as of 2023.

